# Generated by Django 2.2.7 on 2019-12-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=15, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('othername', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('sickness', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=5)),
                ('hall', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
